# https://github.com/marketplace/actions/html5-validator
name: HTML validator
on: [workflow_dispatch]
jobs:
  Validate-html:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: ./ #path to the folder of html/css
        #log_level: INFO, DEBUG, WARNING(DEFAULT)
        #css: true (new css not recognized)
